// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppThread.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// string_edit_dist
List string_edit_dist(const String& str1, const String& str2, Nullable<DataFrame> cost_mat, const String& delim, bool return_alignments);
RcppExport SEXP _lingdist_string_edit_dist(SEXP str1SEXP, SEXP str2SEXP, SEXP cost_matSEXP, SEXP delimSEXP, SEXP return_alignmentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const String& >::type str1(str1SEXP);
    Rcpp::traits::input_parameter< const String& >::type str2(str2SEXP);
    Rcpp::traits::input_parameter< Nullable<DataFrame> >::type cost_mat(cost_matSEXP);
    Rcpp::traits::input_parameter< const String& >::type delim(delimSEXP);
    Rcpp::traits::input_parameter< bool >::type return_alignments(return_alignmentsSEXP);
    rcpp_result_gen = Rcpp::wrap(string_edit_dist(str1, str2, cost_mat, delim, return_alignments));
    return rcpp_result_gen;
END_RCPP
}
// pw_edit_dist
DataFrame pw_edit_dist(const DataFrame& data, Nullable<DataFrame> cost_mat, const String& delim, bool squareform, bool symmetric, bool parallel, int n_threads, bool check_missing_cost);
RcppExport SEXP _lingdist_pw_edit_dist(SEXP dataSEXP, SEXP cost_matSEXP, SEXP delimSEXP, SEXP squareformSEXP, SEXP symmetricSEXP, SEXP parallelSEXP, SEXP n_threadsSEXP, SEXP check_missing_costSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Nullable<DataFrame> >::type cost_mat(cost_matSEXP);
    Rcpp::traits::input_parameter< const String& >::type delim(delimSEXP);
    Rcpp::traits::input_parameter< bool >::type squareform(squareformSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type check_missing_cost(check_missing_costSEXP);
    rcpp_result_gen = Rcpp::wrap(pw_edit_dist(data, cost_mat, delim, squareform, symmetric, parallel, n_threads, check_missing_cost));
    return rcpp_result_gen;
END_RCPP
}
// pw_pmi_dist
List pw_pmi_dist(const DataFrame& data, const String& delim, bool squareform, bool parallel, int n_threads, int max_epochs, double tol, int alignment_max_paths, bool verbose);
RcppExport SEXP _lingdist_pw_pmi_dist(SEXP dataSEXP, SEXP delimSEXP, SEXP squareformSEXP, SEXP parallelSEXP, SEXP n_threadsSEXP, SEXP max_epochsSEXP, SEXP tolSEXP, SEXP alignment_max_pathsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const String& >::type delim(delimSEXP);
    Rcpp::traits::input_parameter< bool >::type squareform(squareformSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type max_epochs(max_epochsSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type alignment_max_paths(alignment_max_pathsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(pw_pmi_dist(data, delim, squareform, parallel, n_threads, max_epochs, tol, alignment_max_paths, verbose));
    return rcpp_result_gen;
END_RCPP
}
// pw_wjd
DataFrame pw_wjd(const DataFrame& data, Nullable<NumericVector> cate_level_weights, Nullable<NumericVector> multi_form_weights, const String& form_delim, const String& cate_delim, bool squareform, bool parallel, int n_threads);
RcppExport SEXP _lingdist_pw_wjd(SEXP dataSEXP, SEXP cate_level_weightsSEXP, SEXP multi_form_weightsSEXP, SEXP form_delimSEXP, SEXP cate_delimSEXP, SEXP squareformSEXP, SEXP parallelSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type cate_level_weights(cate_level_weightsSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type multi_form_weights(multi_form_weightsSEXP);
    Rcpp::traits::input_parameter< const String& >::type form_delim(form_delimSEXP);
    Rcpp::traits::input_parameter< const String& >::type cate_delim(cate_delimSEXP);
    Rcpp::traits::input_parameter< bool >::type squareform(squareformSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(pw_wjd(data, cate_level_weights, multi_form_weights, form_delim, cate_delim, squareform, parallel, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// generate_default_cost_matrix
DataFrame generate_default_cost_matrix(const DataFrame& data, const String& delim);
RcppExport SEXP _lingdist_generate_default_cost_matrix(SEXP dataSEXP, SEXP delimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const String& >::type delim(delimSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_default_cost_matrix(data, delim));
    return rcpp_result_gen;
END_RCPP
}
// long2squareform
DataFrame long2squareform(const DataFrame& data, bool symmetric, double default_diag);
RcppExport SEXP _lingdist_long2squareform(SEXP dataSEXP, SEXP symmetricSEXP, SEXP default_diagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< double >::type default_diag(default_diagSEXP);
    rcpp_result_gen = Rcpp::wrap(long2squareform(data, symmetric, default_diag));
    return rcpp_result_gen;
END_RCPP
}
// check_cost_mat_symbols
StringVector check_cost_mat_symbols(const DataFrame& cost_mat, const DataFrame& data, const String& delim);
RcppExport SEXP _lingdist_check_cost_mat_symbols(SEXP cost_matSEXP, SEXP dataSEXP, SEXP delimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type cost_mat(cost_matSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const String& >::type delim(delimSEXP);
    rcpp_result_gen = Rcpp::wrap(check_cost_mat_symbols(cost_mat, data, delim));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lingdist_string_edit_dist", (DL_FUNC) &_lingdist_string_edit_dist, 5},
    {"_lingdist_pw_edit_dist", (DL_FUNC) &_lingdist_pw_edit_dist, 8},
    {"_lingdist_pw_pmi_dist", (DL_FUNC) &_lingdist_pw_pmi_dist, 9},
    {"_lingdist_pw_wjd", (DL_FUNC) &_lingdist_pw_wjd, 8},
    {"_lingdist_generate_default_cost_matrix", (DL_FUNC) &_lingdist_generate_default_cost_matrix, 2},
    {"_lingdist_long2squareform", (DL_FUNC) &_lingdist_long2squareform, 3},
    {"_lingdist_check_cost_mat_symbols", (DL_FUNC) &_lingdist_check_cost_mat_symbols, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_lingdist(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
